[pytest]
pythonpath = .
tavern-global-cfg = tests/config.yaml

tavern-strict = json:off headers:off

log_cli = true
log_cli_level = INFO

asyncio_mode = auto

filterwarnings =
    ignore::DeprecationWarning